name: Publish lxd-sphinx-extensions to PyPI
on: workflow_dispatch
defaults:
  run:
    working-directory: ./lxd-sphinx-extensions
jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: Store the package
      uses: actions/upload-artifact@v3
      with:
        name: python-package
        path: lxd-sphinx-extensions/dist/
  publish:
    name: Publish to TestPyPI
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/lxd-sphinx-extensions
    permissions:
      id-token: write
    steps:
    - name: Download package
      uses: actions/download-artifact@v3
      with:
        name: python-package
        path: lxd-sphinx-extensions/dist/
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: ./lxd-sphinx-extensions/dist/
